spring:
  profiles:
    group:
      local:
        - local
      dev:
        - dev
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
